In [1]:
import torch

# multinomial

In [15]:
# 概率分布
w = torch.tensor([4, 7, 2, 3], dtype=torch.float)
w

tensor([4., 7., 2., 3.])

In [16]:
# 无放回随机抽取
torch.multinomial(w, num_samples=3)

tensor([3, 2, 1])

In [21]:
# 有放回
torch.multinomial(w,
                  num_samples=5,
                  replacement=True)

tensor([2, 0, 1, 1, 3])

In [38]:
# 概率分布
w = torch.randint(0, 10, (3, 4),
                  dtype=torch.float)
w

tensor([[6., 9., 9., 7.],
        [8., 1., 5., 8.],
        [3., 6., 8., 8.]])

In [40]:
torch.multinomial(w, num_samples=2)

tensor([[1, 3],
        [0, 3],
        [1, 3]])

# gather

In [45]:
a = torch.arange(0, 12).reshape(3, 4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
# 在指定维度抽取多个元素
torch.gather(a, dim=1,
             index=torch.tensor([[0, 3]]))

tensor([[0, 3]])

In [ ]:
# 在指定维度抽取多个元素
torch.gather(a, dim=1,
             index=torch.tensor([[0, 3], [2, 1]]))

tensor([[0, 3],
        [6, 5]])